### ISSUE TITLE
Django 3.2 is end-of-life

### ISSUE THREAD

**Issue by alk3pInjection** [bionade24/abs_cd#22]
Since abs_cd has access to the docker daemon socket, porting to a supported version of django makes sense.

**Comment by alk3pInjection** [comment]
ah I closed this as duplicate since when this issue was proposed I didn't notice that it had already been listed as a todo, so nvm anyway ;)





---- On Sat, 2024-05-25 03:02:41 ***@***.*** wrote ----



@alk3pInjection Is there a more specific reason why you closed it?

It's definitely planned to update & it's also an issue that the library version is EOL.

**Comment by alk3pInjection** [comment]
I've been running and testing #23 (d1e2cc2d5e16) and so far so good.

It's worth noting that the only flaw I ran into is a ZoneInfoNotFoundError which
seems to require Python package tzdata (and pytz?) to be explicitly installed.

Thanks for your fantastic work!

**Comment by alk3pInjection** [comment]
It looks like the repo database files are getting signed [[1]](https://github.com/bionade24/abs_cd/blob/d1e2cc2d5e161bd4987b3c634c3da12b260c1258/makepkg/makepkg.py#L99-L104) when a package is built. I suspect that
the same logic should also apply [here](https://github.com/bionade24/abs_cd/blob/d1e2cc2d5e161bd4987b3c634c3da12b260c1258/cd_manager/models.py#L172-L174) when the database files are touched for removing packages.

**Comment by bionade24** [comment]
> It's worth noting that the only flaw I ran into is a ZoneInfoNotFoundError which
seems to require Python package tzdata (and pytz?) to be explicitly installed.

Can you pls open an issue with logs for this? I haven't run into this bug neither on testing nor on prod yet. The merge blocker for me is that I still have to update the CSS overwrite for the admin panel.
From my log I can also see unallowed hosts in http header warning printing a full traceback in the log, which makes it reather unpleasant to read.

> the same logic should also apply [here](https://github.com/bionade24/abs_cd/blob/d1e2cc2d5e161bd4987b3c634c3da12b260c1258/cd_manager/models.py#L172-L174) when the database files are touched for removing packages.

Nice catch.  I'm unhappy with the structure of the code for a long time, especially on the point that `repo-add` is called from 2 files. But since the main reason I wrote this software deceased & my amount of free time decreased, too, I've never refactored the project. It was only a question of time for something like this to happen.

**Comment by alk3pInjection** [comment]
> haven't run into this bug neither on testing nor on prod yet

I can't really remember the details, but from the search history the error
should look like [[1]](https://stackoverflow.com/questions/71058888), which was thown immediately when a request is received
and returned a 500 error. It's fine if this issue cannot be reproduced since
it might be related to some Dockerfile rewrites in my fork.

> still have to update the CSS overwrite for the admin panel

I personally stick to the original appearance, which doesn't look bad ;)

> unallowed hosts in http header warning printing a full traceback

No such logs here. I've hardcoded the allowed hosts and csrf origins though,
but the original impl doesn't seem to have any problems.

> I'm unhappy with the structure of the code for a long time, especially

Nevertheless this is a good software which really works and has flawlessly
run ~2y for me. Compared to both complete solutions like OBS and hand-
written scripts, it is unique and makes things much easier.
